<?php

namespace App\Controllers;

use App\Models\StudentModel;
use App\Services\LoginService;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Config\Services;
use Config\View;
use Psr\Log\LoggerInterface;

class LoginController extends BaseController
{

    /**
     * @var LoginService
     */
    public $loginService;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->loginService = Services::login();

    }

    public function index()
    {
        if (!$this->request->is('post')) return View('login/index');
        $data = $this->request->getPost();
        var_dump($data);
    }

    public function isLoggedIn()
    {
        $this->loginService->isLoggedIn();
    }

}
