<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use App\Models\StudentModel;
use App\Services\LoginService;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Config\Database;
use Config\Services;
use Config\View;
use Psr\Log\LoggerInterface;

class StudentController extends BaseController
{


    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        try {
            $studentModel = new StudentModel();
            $studentList = $studentModel->findAll();
            return View('student/index', ['data' => $studentList]);
        } catch (\Exception $e) {
            var_dump($e);
            die;
        }
    }


    public function new()
    {
        try {
            if ($this->request->is('Post')) {

                /*$validation = $this->validate([
                    'name' => 'required',
                    'address' => 'required|string',
                    // Add more validation rules for other form fields
                ]);

                if (!$validation) {
                    // If validation fails, return an error response
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Validation failed',
                        'errors' => $this->validator->getErrors()
                    ]);
                }*/

                // If validation passes, get the form data
                $data = $this->request->getPost();
                $studentModel = new StudentModel();
                $studentModel->insert($data);
                return redirect()->to('/student');
            }
            return View('student/new');
        } catch (\Exception $e) {
            var_dump($e->getMessage());
            die;
        }
    }
}